### ISSUE TITLE
дублювання коду, єдине джерело істини

### ISSUE THREAD

**Issue by pecourses** [ArtyomHloba/User-Card#4]
https://github.com/ArtyomHloba/User-Card/blob/bd531f2fb07247f9929f41247c4b6962b4002a58/assets/css/styles.css#L96-L116
- якщо елементи мають переважно спільні властивості, то краще винести їх спільну частину разом, щоб не прописувати кілька разів одне й те саме (і щоб при підтримці вносити правки тільки в одному місці, а не в кількох однакових):
```css
.contact-me-btn,
.hire-me-btn {
  color: #ffff;
  text-decoration: none;
  border: none;
  padding: 5px 0;
  width: 100%;
}

.contact-me-btn {
  background-color: #806f51;
}

.hire-me-btn {
  background-color: #d97961;
}

```
